# Generated by Django 5.2 on 2025-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('organizer', 'Organizer'), ('judge', 'Judge'), ('society', 'Society'), ('sponsor', 'Sponsor')], max_length=20),
        ),
    ]
