# Generated by Django 5.2 on 2025-05-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascon', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('gaming', 'Gaming'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
