# Generated by Django 5.2 on 2025-05-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascon', '0003_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.DO_NOTHING, to='nascon.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('team_name', 'event')},
        ),
    ]
