# Generated by Django 5.2 on 2025-05-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nascon', '0004_team_event_alter_team_team_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventround',
            unique_together={('start_time', 'venue_id')},
        ),
    ]
