# Generated by Django 5.2 on 2025-05-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascon', '0004_team_event_alter_team_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventround',
            unique_together={('round_id', 'event_id'), ('start_time', 'venue_id')},
        ),
    ]
